name: GitHub Actions Demo
run-name: test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.SSH_HOST }}
       username: ${{ secrets.SSH_USERNAME }}
       password: ${{ secrets.SSH_PASSWORD }}
       script: |
        cd html
        git pull origin main
        sudo systemctl restart nginx